version: "3.3"

services:

  web:
    build: ./front-end
    ports:
      - "3000:3000"
    volumes:
      - ./front-end:/app
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo

  mongo:
    image: "mongo"
    restart: always
    ports:
      - 27018:27018
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
